package ob1.eventmanager.bot.event_create_statemachine;

public enum EventEvents {
    STARTED,
    NAME_TYPED,
    NAME_IS_CORRECT,
    NAME_IS_INCORRECT,
    DATE_TYPED,
    DATE_IS_CORRECT,
    DATE_IS_INCORRECT,
    LOCATION_TYPED,
    LOCATION_IS_CORRECT,
    LOCATION_IS_INCORRECT,
    CATEGORY_IS_CORRECT,
    CATEGORY_IS_INCORRECT,
    TEMPLATE_IS_CORRECT,
    TEMPLATE_IS_INCORRECT,
    TEMPLATE_QUESTIONS_WERE_SHOWN,
    TEMPLATE_QUESTIONS_IS_CORRECT,
    TEMPLATE_QUESTIONS_IS_INCORRECT,
    TEMPLATE_EDIT,
    CREATE_CONFIRM_CREATE,
    CREATE_CONFIRM_DISCARD,
    CREATE_CONFIRM_EDIT,
    FINISHED
}
